stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - data/processed
    - src/data/data_ingestion.py
    outs:
    - data/train_test_split
  feature_engineering:
    cmd: python src/data/feature_engineering.py
    deps:
    - data/train_test_split
    - src/data/feature_engineering.py
    outs:
    - data/features
    - models
